apiVersion: apps/v1
kind: Deployment
metadata:
  name: productmicroservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ProductMicroService
  template:
    metadata:
      labels:
        app: ProductMicroService
    spec:
      containers:
      - name: dockersamplerepos
        image: samplecr7.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsnproduct

---
apiVersion: v1
kind: Service
metadata:
  name: productmicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ProductMicroService
